const Images = {
    logo: require('../Image/Logo.png'),
    lock: require('../Image/lock.png'),
    company: require('../Image/company.png'),
    foodbank: require('../Image/foodbank.png'),
    individual: require('../Image/individual.png'),
    needhelp: require('../Image/needhelp.png'),
    statistics: require('../Image/statistics.png'),
    home: require('../Image/home.png'),
    request: require('../Image/request.png'),
    arrowBack: require('../Image/arrowBack.png'),
    plus: require('../Image/plus.png'),
    subtract: require('../Image/subtract.png'),
    dotmenu: require('../Image/dotmenu.png'),
    need_help: require('./need-help.png'),
    logout: require('./logout.png'),
    slider_1: require('./slider_1.jpg'),
    slider_2: require('./slider_2.jpg'),
    slider_3: require('./slider_3.jpg'),
    slider_4: require('./slider_4.jpg'),
    slider_5: require('./slider_5.jpg'),
    slider_6: require('./slider_6.jpg'),
    slider_7: require('./slider_7.jpg'),
    slider_8: require('./slider_8.jpg'),
    slider_9: require('./slider_9.jpg'),
    slider_10: require('./slider_10.jpg'),
    slider_11: require('./slider_11.jpg'),
    splash_img: require('./splash_img.png'),
};
export default Images;
